use_frameworks!

platform :ios, '13.0'

target 'PixCrop_Example' do
#  pod 'PixCrop', :path => '../'
  pod 'PixCrop'
  pod 'SnapKit'

  target 'PixCrop_Tests' do
    inherit! :search_paths

    
  end
end
